### ISSUE TITLE
Получать новых пользователей с codex

### ISSUE THREAD

**Issue by n0str** [codex-team/codex.bot#1]
Продумать API Codex для получения новых пользователей и оповещении о их регистрации.

**Comment by neSpecc** [comment]
@demyashev возьми на себя часть по API

**Comment by n0str** [comment]
Поступило дельное предложение о Notifications API.

> /notify_start - выдает уникальный токен, привязанный к данному чату.

После этого любой текст, отправленный POST запросом по адресу: /notify/<:TOKEN> будет перенаправлен напрямую в соответствующий чат.

TODO: Подумать насчет безопасности. Уникальность генерации токена не обеспечивает достаточной защиты.

**Comment by n0str** [comment]
Referenced in #45

**Comment by n0str** [comment]
Легко реализуется через Notification Module. Остальные вопросы к серверной части. Закрыто.
