### ISSUE TITLE
Команды для Яндекс Метрики

### ISSUE THREAD

**Issue by neSpecc** [codex-team/codex.bot#32]
`/daily` — немедленно выводит статистику за сегодня: DAU, hits
`/monthly` — немедленно выводит статистику за месяц
`/start_daily <TIME>` — запускает ежедневные отчеты по статистику в переданное время (22:45)
`/stop_daily` — останавливает ежедневные отчеты
`/start_weekly <DAY> <TIME>` — запускает еженедельные отчеты в переданный день (1—7) и время
`/stop_weekly <DAY> <TIME>` — запускает еженедельные отчеты в переданный день (1—7) и время

**Comment by n0str** [comment]
**/metrika_get** was implemented.
**TODO**: Rename to /daily

**Comment by n0str** [comment]
**/metrika_add
/metrika_del**
was implemented
