### ISSUE TITLE
Дописать протокол к ссылке, которую выдаёт бот для получения веб-хуков

### ISSUE THREAD

**Issue by illiiiillllilii** [codex-team/codex.bot#44]

**Comment by n0str** [comment]
Fixed in https://github.com/codex-team/codex.bot/pull/42/commits/06d8c19f5dbd3f5734daeafadf1ade7039a7873a

- [ ] @illiiiillllilii 
- [ ] @khaydarov 

Merged to pull-request. Pulled to production server. Able to be tested.

**Comment by n0str** [comment]
#closed
