### ISSUE TITLE
NotifyAPI

### ISSUE THREAD

**Issue by neSpecc** [codex-team/codex.bot#45]
Petr Savchenko, [03 Oct 2016 16:16]: 
Было бы удобно боту сделать что-то вроде NotifyAPI : 

в подключенном чате пишешь команду /notify_start и бот выдает токен для этого чата. Потом с этим токеном можно делать запросы из ПХП или JS. Простой запрос на отправку сообщения в чат

Пример:
```
https://bot.ifmo.su/notify?token=<TOKEN>&message=<MESSAGE>
```

тогда разработчикам можно было бы легко интегрировать всякие уведомления со своих сервисов

типа "Поступила новая заявка в клуб"

или "Ошибка при сохраненнии формы"

**Comment by n0str** [comment]
Предлагаю https://bot.ifmo.su/notify/<TOKEN> и message POST запросом.
Это исключит проблемы с urlencode и размером сообщений у пользователей.

**Comment by n0str** [comment]
Закрыто by #46
