### ISSUE TITLE
License

### ISSUE THREAD

**Issue by epexa** [codex-team/codex.bot#87]
Hi!

Nice work!

But, what is your license for this project?

**Comment by n0str** [comment]
@epexa Thanks for the issue!
We decided to open the code under [MIT ](https://codex.so/licenses)license.

You probably should also check our [contributors community](https://github.com/codex-bot) with SDK's and applications for the Core.

**Comment by epexa** [comment]
@n0str Wonderful! MIT license is the best that can be!
Thanks!
